Market-Crud-Dapper/Models/Product.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Market_Crud_Dapper.Models
{
    public class Product
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Required(ErrorMessage ="Ürün adı girilmesi zorunludur.")]
        [Display(Name ="Ürün Adı")]
        public string ProductName { get; set; }
        [Required(ErrorMessage = "Kategori girilmesi zorunludur.")]
        [Display(Name = "Ürün Kategorisi")]
        public string Category { get; set; }
        [Required(ErrorMessage = "Ürün fiyatı girilmesi zorunludur.")]
        [Display(Name = "Ürün Fiyatı")]
        public decimal ProductPrice { get; set; }
        [Required(ErrorMessage = "Ürün açıklaması girilmesi zorunludur.")]
        [Display(Name = "Ürün Açıklaması")]
        public string ProductDescription { get; set; }
        [Required(ErrorMessage = "Ürün barkodu girilmesi zorunludur.")]
        [Display(Name = "Ürün Barkodu")]
        public string ProductCode { get; set; }

    }
}

Market-Crud-Dapper/Controllers/MarketController.cs
using Dapper;
using Market_Crud_Dapper.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Market_Crud_Dapper.Controllers
{
    public class MarketController : Controller
    {
        // GET: Market
        public SqlConnection dbConnection
        {
            get
            {
                var connection = new SqlConnection(ConfigurationManager.ConnectionStrings["MarketDbConnection"].ConnectionString);
                return connection;
            }
        }
        public ActionResult Index()
        {
            using (var db = dbConnection)
            {
                var dbProducts=db.Query<Product>("SELECT * FROM [dbo].[Product]").ToList();
                return View(dbProducts);
            }
        }
        [HttpGet]
        public ActionResult Edit(int id=0)
        {
            using (var db = dbConnection)
            {
                var dbProduct = db.Query<Product>("SELECT * FROM [dbo].[Product] WHERE [ID]=" + id).SingleOrDefault();
                if (dbProduct != null)
                {
                    return View(dbProduct);
                }
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Edit(Product productModel)
        {
            //try
            //{
                Product product = new Product
                {
                    ProductName=productModel.ProductName,
                    ProductCode=productModel.ProductCode,
                    ProductDescription=productModel.ProductDescription,
                    ProductPrice=productModel.ProductPrice,
                    Category=productModel.Category,
                    Id=productModel.Id
                };
                using (var db = dbConnection)
                {

                    db.Query<Product>("UPDATE [dbo].[Product] SET [ProductName]=@ProductName," +
                                      "[ProductCode]=@ProductCode," +
                                      "[ProductDescription]=@ProductDescription," +
                                      "[ProductPrice]=@ProductPrice,"+
                                      "[Category]=@Category WHERE [Id]=@Id",product);
                }

                return RedirectToAction("Index");
            //}
            //catch
            //{
            //    return HttpNotFound();
            //}

        }
        public ActionResult Delete(int? id)
        {
            //try
            //{
                using (var db=dbConnection)
                {
                    if (id == null)
                    {
                        return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
                    }

                    var dbProduct = db.Query<Product>("SELECT * FROM [dbo].[Product] WHERE [ID]=" + id).SingleOrDefault();
                    if (dbProduct == null)
                    {
                        return HttpNotFound();
                    }
                    else
                    {
                        db.Query<Product>("DELETE FROM [dbo].[Product] WHERE [Id] = " + dbProduct.Id);
                    }
                    //DELETE ACTIONRESULT'IN HTTPPOST PROTOKOLÜ DE YAPILACAK.

                    return RedirectToAction("Index");
                }

            //}
            //catch
            //{
            //    return HttpNotFound();
            //}
        }
        [HttpGet]
        public ActionResult Save()
        {
            return View(new Product());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(Product productModel)
        {
            //try
            //{
               Product product = new Product
                {
                    ProductName=productModel.ProductName,
                    ProductCode=productModel.ProductCode,
                    ProductDescription=productModel.ProductDescription,
                    ProductPrice=productModel.ProductPrice,
                    Category=productModel.Category,
                };
                using (var db = dbConnection)
                {

                    db.Query<Product>("INSERT INTO [dbo].[Product]([ProductName],[ProductCode],[ProductDescription],[ProductPrice],[Category])" +
                                      " VALUES (@ProductName,@ProductCode,@ProductDescription,@ProductPrice,@Category)",product);
                }

                return RedirectToAction("Index");

            //}
            //catch
            //{
            //    return HttpNotFound();
            //}
        }
    }
}

Market-Crud-Dapper/Views/Market/Edit.cshtml
@model Market_Crud_Dapper.Models.Product

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ProductName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Category, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductCode, "", new { @class = "text-danger" })
            </div>
        </div>
        @Html.HiddenFor(z=>z.Id);
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Market-Crud-Dapper/Views/Market/Index.cshtml
@model IEnumerable<Market_Crud_Dapper.Models.Product>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Html.ActionLink("Add Product","Save",new { @class="btn btn-success"})
<table class="table">
    <tr>
        <th>@Html.DisplayNameFor(model => model.ProductName)</th>
        <th>@Html.DisplayNameFor(model => model.Category)</th>
        <th>@Html.DisplayNameFor(model => model.ProductDescription)</th>
        <th>@Html.DisplayNameFor(model => model.ProductCode)</th>
        <th>@Html.DisplayNameFor(model => model.ProductPrice)</th>
        <th>Ayarlar</th>
    </tr>
    @foreach (var products in Model)
        {
            <tr>
                <td>@products.ProductName</td>
                <td>@products.Category</td>
                <td>@products.ProductDescription</td>
                <td>@products.ProductCode</td>
                <td>@products.ProductPrice</td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new {id = products.Id}, new {@class = "btn btn-warning"})
                    @Html.ActionLink("Delete", "Delete", new {id = products.Id}, new {@class = "btn btn-danger"})
                </td>
            </tr>
        }

</table>

Market-Crud-Dapper/Views/Market/Save.cshtml
@model Market_Crud_Dapper.Models.Product

@{
    ViewBag.Title = "Save";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Save</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ProductName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Category, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Market-Crud-Dapper/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MarketApp", "Index", "Market", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>